"""
Date Calculation Processor for deadline-alerts
Detector: D2_date_calculation
Generated by: legal_skill_optimizer_lite v3.1.0

处理逻辑:
- 根据案件类型、阶段计算各项程序期限
- 处理节假日顺延规则
- 计算剩余天数并标注紧急程度

风险说明:
- 节假日数据可能不完整或过时，需人工复核
- 特殊情形（鉴定、中止、延期）需人工判断
"""

from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, TypedDict


class DateCalcInput(TypedDict, total=False):
    case_type: str  # 民事/商事/行政
    case_stage: str  # 一审/二审/再审/执行
    key_date: str  # 关键日期 (YYYY-MM-DD)
    date_type: str  # 判决日/收到日/立案日
    party_type: str  # 自然人/法人
    procedure_type: str  # 普通程序/简易程序
    special_circumstances: List[str]  # 特殊情形


class DateCalcOutput(TypedDict, total=False):
    ok: bool
    deadlines: List[Dict[str, Any]]
    warnings: List[str]
    needs_human_review: bool


# 期限规则配置 - 依据《民事诉讼法》《民法典》及相关司法解释
DEADLINE_RULES = {
    "民事": {
        "一审": {
            "上诉期": {
                "判决": {"duration": 15, "unit": "天", "law": "民诉法第171条", "start_from": "送达次日"},
                "裁定": {"duration": 10, "unit": "天", "law": "民诉法第171条", "start_from": "送达次日"},
            },
            "举证期": {
                "普通程序": {"duration": 15, "unit": "天", "law": "民诉解释第99条", "min_days": 15},
                "简易程序": {"duration": 15, "unit": "天", "law": "简易程序规定", "max_days": 15},
                "小额诉讼": {"duration": 7, "unit": "天", "law": "小额诉讼规定", "max_days": 7},
            },
            "答辩期": {"duration": 15, "unit": "天", "law": "民诉法第128条", "start_from": "收到起诉状副本次日"},
        },
        "二审": {
            "举证期": {"duration": 10, "unit": "天", "law": "民诉解释第99条", "note": "提供新证据的二审案件不得少于10日"},
        },
        "执行": {
            "申请执行期": {"duration": 2, "unit": "年", "law": "民诉法第246条", "start_from": "履行期间最后一日起/生效之日起"},
        },
        "再审": {
            "申请再审期": {"duration": 6, "unit": "月", "law": "民诉法第205条/第216条", "start_from": "判决裁定生效之日起"},
        },
    },
    "商事": {
        "一审": {
            "上诉期": {
                "判决": {"duration": 15, "unit": "天", "law": "民诉法第171条"},
                "裁定": {"duration": 10, "unit": "天", "law": "民诉法第171条"},
            },
        },
    },
    "行政": {
        "一审": {
            "上诉期": {"duration": 15, "unit": "天", "law": "行政诉讼法第58条"},
        },
    },
}

# 诉讼时效规则 - 依据《民法典》
STATUTE_OF_LIMITATIONS = {
    "普通诉讼时效": {"duration": 3, "unit": "年", "law": "民法典第188条", "start_from": "知道或应当知道权利受损及义务人之日起"},
    "最长保护期": {"duration": 20, "unit": "年", "law": "民法典第188条", "start_from": "权利受损之日起"},
    "分期履行": {"start_from": "最后一期履行期限届满之日起", "law": "民法典第189条"},
    "中止": {"condition": "最后6个月内", "effect": "原因消除后满6个月时效届满", "law": "民法典第194条"},
    "中断": {"triggers": ["提出履行请求", "同意履行", "提起诉讼/仲裁"], "effect": "重新计算", "law": "民法典第195条"},
}

# 期间计算规则 - 依据《民事诉讼法》第85-86条
PERIOD_CALCULATION_RULES = {
    "起算规则": "从送达次日/次日起算，送达当日不计算在内",
    "节假日顺延": "期间届满最后一日为法定休假日的，顺延至休假日后的第一日",
    "在途时间": "诉讼文书在期满前交邮的，不算过期",
    "涉外案件": "答辩期30日，其他特殊规定优先适用",
}

# 法条原文引用
LAW_CITATIONS = {
    "民诉法第171条": "当事人不服地方人民法院第一审判决的，有权在判决书送达之日起十五日内向上一级人民法院提起上诉。当事人不服地方人民法院第一审裁定的，有权在裁定书送达之日起十日内向上一级人民法院提起上诉。",
    "民诉法第246条": "申请执行的期间为二年。申请执行时效的中止、中断，适用法律有关诉讼时效中止、中断的规定。前款规定的期间，从法律文书规定履行期间的最后一日起计算；法律文书规定分期履行的，从规定的每次履行期间的最后一日起计算；法律文书未规定履行期间的，从法律文书生效之日起计算。",
    "民法典第188条": "向人民法院请求保护民事权利的诉讼时效期间为三年。诉讼时效期间自权利人知道或者应当知道权利受到损害以及义务人之日起计算。但是，自权利受到损害之日起超过二十年的，人民法院不予保护。",
}

# 节假日列表 (示例，需接入官方数据源)
HOLIDAYS_2026 = [
    "2026-01-01",  # 元旦
    "2026-02-17", "2026-02-18", "2026-02-19",  # 春节
    "2026-04-05",  # 清明
    "2026-05-01",  # 劳动节
    "2026-06-19",  # 端午
    "2026-09-25",  # 中秋
    "2026-10-01", "2026-10-02", "2026-10-03",  # 国庆
]


def is_working_day(date: datetime) -> bool:
    """判断是否为工作日"""
    # 周末判断
    if date.weekday() >= 5:  # 5=周六, 6=周日
        return False
    
    # 节假日判断
    date_str = date.strftime("%Y-%m-%d")
    if date_str in HOLIDAYS_2026:
        return False
    
    return True


def get_next_working_day(date: datetime) -> datetime:
    """获取下一个工作日"""
    next_day = date + timedelta(days=1)
    while not is_working_day(next_day):
        next_day += timedelta(days=1)
    return next_day


def calculate_deadline(
    start_date: datetime,
    days: int,
    consider_holiday: bool = True
) -> datetime:
    """
    计算截止日期，处理节假日顺延
    
    TODO: 完善节假日顺延逻辑
    """
    deadline = start_date + timedelta(days=days)
    
    if consider_holiday:
        # 如果截止日是节假日，顺延至下一个工作日
        while not is_working_day(deadline):
            deadline = get_next_working_day(deadline)
    
    return deadline


def get_deadline_rules(case_type: str, case_stage: str) -> Dict[str, Any]:
    """获取期限规则"""
    return DEADLINE_RULES.get(case_type, {}).get(case_stage, {})


def calculate_deadline_with_law(
    start_date: datetime,
    deadline_name: str,
    rule: Dict[str, Any],
    warnings: List[str]
) -> Dict[str, Any]:
    """
    计算特定期限并附加法条依据
    """
    duration = rule.get("duration", 0)
    unit = rule.get("unit", "天")
    law = rule.get("law", "")
    start_from = rule.get("start_from", "")
    
    # 计算截止日期
    if unit == "天":
        deadline_date = calculate_deadline(start_date, duration)
    elif unit == "月":
        # 简化处理：按30天/月计算
        deadline_date = start_date + timedelta(days=duration * 30)
    elif unit == "年":
        # 简化处理：按365天/年计算
        deadline_date = start_date + timedelta(days=duration * 365)
    else:
        deadline_date = start_date
    
    # 计算剩余天数
    remaining_days = (deadline_date - datetime.now()).days
    
    # 确定紧急程度
    if remaining_days < 0:
        urgency = "🔴已逾期"
    elif remaining_days <= 3:
        urgency = "🔴紧急（不足3天）"
    elif remaining_days <= 7:
        urgency = "🟠高危（3-7天）"
    elif remaining_days <= 15:
        urgency = "🟡警告（7-15天）"
    else:
        urgency = "🟢正常"
    
    return {
        "name": deadline_name,
        "duration": f"{duration}{unit}",
        "start_date": start_date.strftime("%Y-%m-%d"),
        "deadline": deadline_date.strftime("%Y-%m-%d"),
        "remaining_days": remaining_days,
        "urgency": urgency,
        "law": law,
        "law_content": LAW_CITATIONS.get(law, ""),
        "start_from": start_from,
        "notes": rule.get("note", ""),
    }


def process(payload: DateCalcInput) -> DateCalcOutput:
    """
    主处理函数 - 依据《民事诉讼法》《民法典》计算期限
    """
    warnings: List[str] = []
    deadlines: List[Dict[str, Any]] = []
    
    # 输入校验
    case_type = payload.get("case_type", "")
    case_stage = payload.get("case_stage", "")
    key_date_str = payload.get("key_date", "")
    key_date_type = payload.get("date_type", "")
    
    if not all([case_type, case_stage, key_date_str]):
        warnings.append("缺少必填参数: case_type, case_stage, key_date")
        return {
            "ok": False,
            "deadlines": deadlines,
            "warnings": warnings,
            "needs_human_review": True,
        }
    
    # 解析日期
    try:
        key_date = datetime.strptime(key_date_str, "%Y-%m-%d")
    except ValueError:
        warnings.append("日期格式错误，必须使用 YYYY-MM-DD 格式")
        return {
            "ok": False,
            "deadlines": deadlines,
            "warnings": warnings,
            "needs_human_review": True,
        }
    
    # 获取期限规则
    rules = get_deadline_rules(case_type, case_stage)
    
    if not rules:
        warnings.append(f"未找到 {case_type}/{case_stage} 的期限规则，请核实案件类型和阶段")
        return {
            "ok": False,
            "deadlines": deadlines,
            "warnings": warnings,
            "needs_human_review": True,
        }
    
    # 计算各项期限
    for deadline_name, rule_config in rules.items():
        if isinstance(rule_config, dict) and "duration" in rule_config:
            # 简单规则
            deadline_info = calculate_deadline_with_law(
                key_date, deadline_name, rule_config, warnings
            )
            deadlines.append(deadline_info)
        elif isinstance(rule_config, dict):
            # 嵌套规则（如上诉期分为判决/裁定）
            for sub_name, sub_rule in rule_config.items():
                if isinstance(sub_rule, dict) and "duration" in sub_rule:
                    full_name = f"{deadline_name}({sub_name})"
                    deadline_info = calculate_deadline_with_law(
                        key_date, full_name, sub_rule, warnings
                    )
                    deadlines.append(deadline_info)
    
    # 添加期间计算规则说明
    warnings.append("期间计算规则：")
    warnings.append(f"1. {PERIOD_CALCULATION_RULES['起算规则']}")
    warnings.append(f"2. {PERIOD_CALCULATION_RULES['节假日顺延']}")
    warnings.append(f"3. {PERIOD_CALCULATION_RULES['在途时间']}")
    warnings.append("所有计算结果仅供参考，必须以法院实际通知为准")
    
    return {
        "ok": True,
        "deadlines": deadlines,
        "warnings": warnings,
        "needs_human_review": True,  # 必须人工复核
    }


def _basic_test() -> None:
    """基础测试"""
    payload: DateCalcInput = {
        "case_type": "民事",
        "case_stage": "一审",
        "key_date": "2026-03-14",
        "date_type": "判决日",
        "party_type": "自然人",
    }
    result = process(payload)
    assert "ok" in result
    assert "deadlines" in result
    assert "needs_human_review" in result
    print("Date calc processor stub self-test passed")


if __name__ == "__main__":
    _basic_test()
